### ISSUE TITLE
NWS Forecasts not working

### ISSUE THREAD

**Issue by daf** [NOAA-ORR-ERD/WebGnomeClient#1]
Since updating to the latest HEAD (e2d8361607d4aa0e9f9a36) I am unable to get NWS Forecasts working.  I have been trying for the last 24 hours on my end, so might not just be a down provider issue.  Any click results in "Error! No NWS forecast data found"

**Comment by naomiconnolly-noaa** [comment]
11cfbc35c66fd6821b549af67f0bd991d5a33306 should fix this one.
