### ISSUE TITLE
Issue about manual spill input

### ISSUE THREAD

**Issue by dkobashi** [NOAA-ORR-ERD/WebGnomeClient#10]
Hi,

On WebGnome client,  I tried to set up spill information (non-weathering for simplicity). When I tried to place the starting position of Latitude and Longitude (Lat=29.0, Lon=-94.0 (or 266.0), I had an error saying "Error! Start or End position are outside of supported area". I am positive that the area is within my model domain (see attached screenshot).

When I tried to place the spill location "on map", no map is shown and Latitude and Longitude information on the bottom left is NaN (see attached screenshot). I wonder what I did wrong. I loaded coastline file and gridded wind and current prior to the spill setting. Is there anything else I need to include to set up the spill?

Thanks,

DJ Kobashi
 

![error1](https://cloud.githubusercontent.com/assets/8714949/25447382/9a95c9f0-2a7a-11e7-86d0-435150b622c9.png)

![erro2](https://cloud.githubusercontent.com/assets/8714949/25447388/9e2fa91e-2a7a-11e7-8406-6f9eb975b8b4.png)

**Comment by naomiconnolly-noaa** [comment]
This has been fixed with 98cb2b6291f55dc19138dd2b195a21844ada6d34. Pygnome also has had a fix applied related to this. Not 100% sure it's on github yet though.
