### ISSUE TITLE
Issue about install conda_requirements.txt

### ISSUE THREAD

**Issue by pepito232** [NOAA-ORR-ERD/WebGnomeClient#11]
I'm following all the steps. I've got a Redis server and Anaconda software.

When I was trying to install webgnome API, I wrote "conda install --file conda_requirements.txt" and Command Prompt showed me a PackageNotFoundError...
Why? I've got a pygnome folder.

Thanks,

P.

**Comment by naomiconnolly-noaa** [comment]
What does `conda config --get channels` tell you?

You want it to look something like:

> --add channels 'defaults'   # lowest priority
> --add channels 'conda-forge'
> --add channels 'noaa-orr-erd'   # highest priority

**Comment by pepito232** [comment]
Thank you very match, I solved the problem when I added conda-forge and noaa--orr-erd channels.
Now I' ve got a problem with install requirements.txt from WebgnomeAPI. 
The following error is:

> 'Could not find a version that satisies the requirement PyGnome (from -r requirements.txt line11)) (from versions: )
> No matching distribution found for Pygnome (from -r requirements.txt (line 11))'.

First, sorry for the inconveniences, I'm new at this...

Thanks,

P.

**Comment by pepito232** [comment]
@NathanWilkins-NOAA 
![error](https://cloud.githubusercontent.com/assets/28751197/26236954/4c85dca4-3c73-11e7-81cb-27092d8ccc17.png)

**Comment by naomiconnolly-noaa** [comment]
You can find that dependency here https://github.com/NOAA-ORR-ERD/PyGnome. It isn't distributed on pip or conda yet.
