### ISSUE TITLE
Internal server error issue

### ISSUE THREAD

**Issue by dharanidharan12** [NOAA-ORR-ERD/WebGnomeClient#13]
Configured using this link
**https://github.com/NOAA-ORR-ERD/WebGnomeClient/blob/master/API_SETUP.md**

cd webgnomeapi

I configured both PyGnome and WebGnomeAPI 
While Running this line:
**pserve --reload config-example.ini**

Getting error like
**from gnome.movers import PyMover
ImportError: cannot import name PyMover**

I also  tried in file as 
 **from gnome.movers import ***
It runs and throws the url link, while running it ,
 **Showing Internal Server Error**

Why This error occurs, What I did wrong ?.. 

Please Help. Thanks in Advance!

**Comment by naomiconnolly-noaa** [comment]
What does running the following in a python shell show you?
``` python
import gnome
dir(gnome.movers)
```

**Comment by dharanidharan12** [comment]
['CatsMover', 'ComponentMover', 'CurrentCycleMover', 'CyMover', 'GridCurrentMover', 'GridWindMover', 'IceAwareRandomMover', 'IceMover', 'IceWindMover', 'Mover', 'Process', 'ProcessSchema', 'PyCurrentMover', 'PyWindMover', 'RandomMover', 'RandomVerticalMover', 'RiseVelocityMover', 'ShipDriftMover', 'SimpleMover', 'TamocRiseVelocityMover', 'WindMover', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'constant_wind_mover', 'current_movers', 'movers', 'py_current_movers', 'py_wind_movers', 'random_movers', 'ship_drift_mover', 'simple_mover', 'vertical_movers', 'wind_mover_from_file', 'wind_movers']

while running in shell, it shows

**Comment by naomiconnolly-noaa** [comment]
Well that definitely doesn't include a PyMover. What version of pygnome do you have installed?

**Comment by dharanidharan12** [comment]
**gnome-terminal --version**
GNOME Terminal 3.6.2

**apt-cache show gnome-shell | grep Version**
Version: 3.10.4-0ubuntu5.2
Version: 3.10.4-0ubuntu5

which version of pygnome is required for PyMover. Please Mention the version.

**Comment by naomiconnolly-noaa** [comment]
@jay-hennen @JamesMakela-NOAA any idea when we added PyMover?

**Comment by naomiconnolly-noaa** [comment]
It look like it's not released yet (should be updated soon). You can get this working in the mean time by adding `PyMover` to the end of line 5 in `py_gnome/gnome/movers/__init__.py`.
