### ISSUE TITLE
NWS Forecast retrieval error results in permanent disabling of Save button

### ISSUE THREAD

**Issue by daf** [NOAA-ORR-ERD/WebGnomeClient#2]
In the Wind popup, when NWS Forecasts result in an error (see #1), the Save button becomes disabled permanently for the life of the popup.  Switching to constant/variable tabs does not re-enable Save, the popup must be closed and re-opened.

**Comment by naomiconnolly-noaa** [comment]
4ef65b3b1440f8272f4df8d6ecf58bcdee32b439 should fix this. Thank you, Dave.

**Comment by NathanWilkins-NOAA** [comment]
x
