### ISSUE TITLE
Weathering/Trajectory buttons inactive after New Model

### ISSUE THREAD

**Issue by daf** [NOAA-ORR-ERD/WebGnomeClient#3]
Selecting Model -> New from the menu, the Weathering/Trajectory/W+T buttons no longer respond to clicks.

**Comment by daf** [comment]
and doing Model -> New a second time adds a second configuration panel:

![2015-09-30-15 22 39](https://cloud.githubusercontent.com/assets/228715/10203971/20ec6c4c-6787-11e5-9e28-3e42001d41cf.png)

**Comment by daf** [comment]
This can happen across sessions as well - close and reload the browser, you'll see "rewound model" in the log messages, and this behavior occurs.

**Comment by naomiconnolly-noaa** [comment]
Could you post your browser's javascript console when this occures? Most
likely a javascript error, that won't show up in the logging panel.

If you're unfamiliar with what I mean:
https://developers.google.com/web/tools/javascript/console/console-ui

**Comment by daf** [comment]
Nothing out of the ordinary - these flot errors happen on every New Model:

![2015-09-30-15 41 16](https://cloud.githubusercontent.com/assets/228715/10204445/c4e8a62e-6789-11e5-9ad3-ba9d0fb9d61b.png)

**Comment by naomiconnolly-noaa** [comment]
Is this always happening? Are you on 0b264d655782b23625f85d7c9959c8f5ab63beae?

**Comment by daf** [comment]
Yes, that commit is in my branch's history (I have some local, specific purpose commits as well).  I just did an `npm install` / `grunt install` again just in case, same errors there.

**Comment by naomiconnolly-noaa** [comment]
py_gnome and webgnomeapi are at their latest and the tests pass?

**Comment by daf** [comment]
I was a few commits behind on both, but updated now.  py_gnome tests pass, not sure how to run WebGnomeAPI's.  (py.test fails with a `ConftestImportError`)

**Comment by naomiconnolly-noaa** [comment]
py.test should run the webgnomeapi's tests. Want to post the stack trace for the conftest import error in a gist?

**Comment by daf** [comment]
Sure, https://gist.github.com/daf/031eeb7b94e92e1d86f4

Although I'm not sure it's related.  I'll bisect the front-end and see if i can find it.

**Comment by daf** [comment]
Ugh, now I can't reproduce this bug at all!  Perhaps I had some out of date results of less compilation or similar.  I'm sorry for the goose chase!
